import { moduleTool, type AppModule } from "./types";

export const intifaceModule: AppModule = {
  id: "intiface",
  name: "Intiface",
  description: "Intiface haptics, device control, play modes, media sync, and funscript tools.",
  kind: "media",
  defaultEnabled: false,
  defaultSettings: {
    intifaceEnabled: false,
    intifaceAiEnabled: true,
    intifaceConnected: false,
    intifaceAiTtsSyncEnabled: false,
    intifaceAiTtsSyncOffsetMs: 0,
    intifaceAiTtsSyncTimeoutMs: 1200,
    intifaceAiSyncStartLeadMs: 1200,
    intifaceAiTtsInterruptPolicy: "grace",
    intifaceDebugLoggingEnabled: false,
    intifaceSelectedMode: "basic",
    intifaceEnabledModes: ["basic"],
    intifaceTimelinePattern: "sine",
    intifaceTimelinePlaying: false,
    intifacePatternDurationMs: 5000,
    intifacePatternMin: 0,
    intifacePatternMax: 100,
    intifacePatternCycles: 3,
    intifaceTimelineScrubberMs: 0,
    intifaceTimelineBlocks: [],
    intifaceModeBuilderId: "",
    intifaceModeBuilderName: "",
    intifaceModeBuilderPersonality: "",
    intifaceModeBuilderDescription: "",
    intifaceModeBuilderSystemPrompt: "",
    intifaceModeBuilderIcon: "fa-star",
    intifaceModeBuilderColor: "#6464ff",
    intifaceModeBuilderMultiplier: 1,
    intifaceMediaSearch: "",
    intifaceMediaType: "all",
    intifaceMediaSort: "name-asc",
    intifaceSelectedFunscript: "",
    intifaceFunscriptJson: "",
    intifaceFunscriptUseSmooth: true,
    intifaceFunscriptSmoothWindow: 5,
    intifaceFunscriptUseScale: false,
    intifaceFunscriptScalePercent: 100,
    intifaceFunscriptUseShift: false,
    intifaceFunscriptShiftMs: 0,
    intifaceFunscriptUseDecimate: true,
    intifaceFunscriptDecimateGapMs: 40,
    intifaceFunscriptDeviceProfile: "auto",
    intifaceFunscriptOptimizeIntensity: 100,
    intifaceFunscriptAiInstructions: "",
    intifaceMenuSyncOffsetMs: 0,
    intifaceMenuIntensity: 100,
    intifaceGlobalIntensity: 100,
    intifacePollingRateHz: 30,
    intifaceMenuVideoOpacity: 100,
    intifaceMenuWidth: 100,
    intifaceMenuZIndex: 1,
    intifaceMenuLoop: false,
    intifaceGlobalInvert: false,
    intifaceAutoConnect: false,
    intifaceMenuPosition: "top",
    assetBaseUrl: "/assets/modules/intiface"
  },
  tools: [moduleTool("intiface.play", "Start a consented Intiface haptic pattern."), moduleTool("intiface.stop", "Stop active Intiface haptic playback.")],
  hooks: {
    getPromptBlocks({ settings }) {
      if (settings.intifaceAiEnabled === false) return [];
      return [{
        id: "intiface-ai-actions",
        name: "Intiface Device Actions",
        enabled: true,
        role: "system",
        position: "after-history",
        priority: 46,
        content: "If Intiface device control is useful and consented to by the user, use the Intiface tools. Keep intensity conservative unless the user explicitly asks otherwise."
      }];
    }
  }
};
