import type { AppModule } from "./types";

export const vrmModule: AppModule = {
  id: "vrm",
  name: "VRM",
  description: "VRM avatar models, animation mapping, hitboxes, lighting, and stage controls.",
  kind: "media",
  defaultEnabled: false,
  defaultSettings: {
    vrmFollowCamera: false,
    vrmFollowCursor: false,
    vrmBlink: false,
    vrmNaturalIdle: true,
    vrmTtsLipsSync: false,
    vrmAutoSendHitboxMessage: false,
    vrmChestJiggleEnabled: false,
    vrmChestJiggleAccelerometer: false,
    vrmChestJiggleStrength: 35,
    vrmChestJiggleSoftness: 45,
    vrmChestJiggleGravity: 20,
    vrmChestJiggleVertical: 100,
    vrmChestJiggleSway: 100,
    vrmChestJiggleDepth: 70,
    vrmHitboxCallModeSyncDelayMs: 220,
    vrmHitboxCallModeWaitTtsStartMs: 4500,
    vrmModelZIndex: 4,
    vrmHitboxes: false,
    vrmModelsCache: false,
    vrmAnimationsCache: false,
    vrmShowGrid: false,
    vrmLightColor: "#ffffff",
    vrmLightIntensity: 100,
    vrmLightPreset: "studio",
    vrmRimLightEnabled: true,
    vrmRimLightColor: "#d9e8ff",
    vrmRimLightIntensity: 85,
    vrmFillLightIntensity: 35,
    vrmAmbientLightIntensity: 45,
    vrmKeyLightAngle: 35,
    vrmLightingContrast: 55,
    vrmSelectedAgentId: "",
    vrmModelMap: {},
    vrmModelSettings: {},
    vrmModelScale: 3,
    vrmModelPositionX: 0,
    vrmModelPositionY: 0,
    vrmModelRotationX: 0,
    vrmModelRotationY: 0,
    vrmDefaultExpression: "",
    vrmDefaultMotion: "",
    vrmBlendShapeGroupName: "",
    vrmEnabled: false,
    vrmShowStatus: false,
    assetBaseUrl: "/assets/modules/vrm"
  },
  hooks: {}
};
